# Generated by Django 5.1.5 on 2025-04-06 16:38

import storages.backends.gcloud
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='input_video',
            field=models.FileField(storage=storages.backends.gcloud.GoogleCloudStorage, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='output_image',
            field=models.FileField(blank=True, null=True, storage=storages.backends.gcloud.GoogleCloudStorage, upload_to='progress_images/'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='output_video',
            field=models.FileField(blank=True, null=True, storage=storages.backends.gcloud.GoogleCloudStorage, upload_to='pose_videos/'),
        ),
    ]
